#!/usr/bin/env python

import numpy as np
from xaosim.scexao_shmlib import shm

nfrm = 100 # number of frames to average

cam = shm('/tmp/kcam.im.shm') # the source of data

im = cam.get_data().astype(float)


for ii in range(nfrm-1):
    im += cam.get_data()

im /= float(nfrm)

drk = shm('/tmp/kcam_dark.im.shm', data=im.astype(np.dtype('uint16')))

cam.close()
drk.close()
